"""Print LaTeX tables from simulation Moran summary CSVs.

Run after scripts/moran_simulation_analysis.py.

Usage
-----
    python scripts/make_simulation_tables.py --table moran-main
    python scripts/make_simulation_tables.py --table enrichment
    python scripts/make_simulation_tables.py --table appendix-morans
    python scripts/make_simulation_tables.py --table dt
    python scripts/make_simulation_tables.py --table dt-extended
"""

import argparse
from pathlib import Path

import pandas as pd

SUMMARY_DIR = Path(".")
SETTING = "1000_features_sparse_sparsity"
MAIN_CLASSES = [6, 7, 8, 9, 10]
HIGH_CLASSES  = [8, 9, 10]


def read_summary(experiment):
    for name in [
        f"v2{experiment}_simulation_scores.csv",
        f"{experiment}_simulation_scores.csv",
        f"{experiment}_simulation_scores_dt.csv",
    ]:
        p = SUMMARY_DIR / name
        if p.exists():
            df = pd.read_csv(p)
            ok = df[df["status"].eq("ok")].copy()
            if ok.empty:
                statuses = df["status"].value_counts().to_dict()
                raise ValueError(
                    f"{p}: no rows with status='ok'. Statuses found: {statuses}\n"
                    "Re-run moran_simulation_analysis.py to regenerate this file."
                )
            if "bias2_moran_I" not in ok.columns:
                raise ValueError(
                    f"{p}: missing expected columns (bias2_moran_I not found).\n"
                    "This file was generated by an older analysis script. "
                    "Re-run moran_simulation_analysis.py to regenerate it."
                )
            return ok

    raise FileNotFoundError(f"Missing summary CSV for {experiment} in {SUMMARY_DIR}")


def mean_sd(x, digits=3, scale=1):
    x = pd.Series(x).dropna().astype(float) * scale
    return rf"\({x.mean():.{digits}f} \pm {x.std(ddof=1):.{digits}f}\)"

def mean_only(x, digits=3, scale=1):
    x = pd.Series(x).dropna().astype(float) * scale
    return rf"\({x.mean():.{digits}f}\)"


def table_moran_main():
    rows = []
    for C in MAIN_CLASSES:
        df = read_summary(f"{C}_class_{SETTING}")
        rows.append([
            str(C),
            mean_sd(df["bias2_moran_I"]),
            mean_sd(df["mse_moran_I"]),
            mean_sd(df["var_moran_I"]),
            mean_sd(df["var_depth_bv_moran_I"]),
        ])

    print(r"""\begin{table}[t]
\centering
\caption{Spatial autocorrelation of simulation error components in the 1000 sparse-feature simulation. Values are mean $\pm$ SD across generating NDs.}
\label{tab:simulation-spatial}
\small
\renewcommand{\arraystretch}{1.25}
\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}ccccc@{}}
\toprule
Classes & $I$ (bias$^2$) & $I$ (loss) & $I$ (var) & $I_{xy}$ (depth, var) \\
\midrule""")
    for row in rows:
        print(" & ".join(row) + r" \\")
    print(r"""\bottomrule
\end{tabular*}
\end{table}""")


def table_enrichment():
    rows = []
    for C in MAIN_CLASSES:
        df = read_summary(f"{C}_class_{SETTING}")
        rows.append([
            str(C),
            mean_only(df["bias2_top10_recall_nearest"], digits=1, scale=100),
            mean_only(df["bias2_top10_auc_by_nearness"]),
            mean_only(df["var_top10_recall_nearest"], digits=1, scale=100),
            mean_only(df["var_top10_auc_by_nearness"]),
            mean_only(df["mse_top10_recall_nearest"], digits=1, scale=100),
            mean_only(df["mse_top10_auc_by_nearness"]),
        ])

    print(r"""\begin{table}[t]
\centering
\caption{Retrieval of low-error structures near the generating ND in the 1000 sparse-feature simulation. Recall is the percentage of the lowest-error decile found inside the nearest 10\% of structures to the generating ND. AUC uses distance to the generating ND to rank all candidate structures. Values are mean $\pm$ SD across generating NDs.}
\label{tab:nearest-generator-enrichment}
\small
\renewcommand{\arraystretch}{1.25}
\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}ccccccc@{}}
\toprule
& \multicolumn{2}{c}{Squared bias} & \multicolumn{2}{c}{Variance} & \multicolumn{2}{c}{Squared prob.\ loss} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
Classes & Recall & AUC & Recall & AUC & Recall & AUC \\
\midrule""")
    for row in rows:
        print(" & ".join(row) + r" \\")
    print(r"""\bottomrule
\end{tabular*}
\end{table}""")

_APPENDIX_SETTINGS = [
    ("10-feat (dense)",    "10_features_dense_sparsity",    True),
    ("1000-feat (sparse)", "1000_features_sparse_sparsity", True),
    ("1000-feat (dense)",  "1000_features_dense_sparsity",  True),
]

_APPENDIX_METRICS = [
    (r"Moran's $I$ ($\mathrm{bias}^2$)",                        "bias2_moran_I"),
    (r"Moran's $I$ (variance)",                                  "var_moran_I"),
    (r"Moran's $I$ (squared probability loss)",                  "mse_moran_I"),
    (r"Bivariate Moran's $I$ (depth, $\mathrm{bias}^2$)",       "bias2_depth_bv_moran_I"),  # sparse only
    (r"Bivariate Moran's $I$ (depth, variance)",                 "var_depth_bv_moran_I"),
]


def table_appendix_morans():
    print(r"""\begin{table}[t]
\centering
\caption{Spatial autocorrelation of bias--variance components in the depth-weighted tokeniser
embedding across 50 simulations at 6 and 7 classes across all four feature settings. The 1000-feature sparse results are reproduced here
for completeness, as in the main text.}
\label{tab:morans-appendix}
\small
\setlength{\tabcolsep}{4pt}
\renewcommand{\arraystretch}{1.25}
\begin{tabular}{@{}p{0.19\textwidth}p{0.39\textwidth}p{0.17\textwidth}p{0.17\textwidth}@{}}
\toprule
Setting & Metric & 6 classes & 7 classes \\
\midrule""")

    for i, (label, suffix, is_sparse) in enumerate(_APPENDIX_SETTINGS):
        if i:
            print(r"\midrule")
        dfs = {}
        for C in [6, 7]:
            dfs[C] = read_summary(f"{C}_class_{suffix}")

        first = True
        for metric_label, col in _APPENDIX_METRICS:
            # bivariate depth-bias2 row only for the sparse setting
            if col == "bias2_depth_bv_moran_I" and not is_sparse:
                continue
            c6 = mean_sd(dfs[6][col])
            c7 = mean_sd(dfs[7][col])
            if first:
                print(f"{label} & {metric_label} & {c6} & {c7} \\\\")
                first = False
            else:
                print(f" & {metric_label} & {c6} & {c7} \\\\")

    print(r"""\bottomrule
\end{tabular}
\end{table}""")


_DT_SETTINGS = [
    ("10-feat (dense)",    "10_features_dense_sparsity"),
    ("1000-feat (sparse)", "1000_features_sparse_sparsity"),
    ("1000-feat (dense)",  "1000_features_dense_sparsity"),
]


def table_dt():
    header = (
        r"\begin{table}[t]" + "\n"
        r"\centering" + "\n"
        r"\caption{Spatial diagnostics for the decision-tree setting at 6 classes, across"
        r" the three feature settings of Appendix~\ref{appendix:ablation}, over the same"
        r" 50 generators as the main study. $I$ is univariate Moran's $I$, $I_{xy}$ is"
        r" the bivariate Moran's $I$ between variance and depth, and $r^2$ is the squared"
        r" Pearson correlation between per-tree squared bias and variance. Values are"
        r" mean $\pm$ SD, and every $I$ is significant at $p \le 0.001$.}" + "\n"
        r"\label{tab:dt-simulation}" + "\n"
        r"\small" + "\n"
        r"\renewcommand{\arraystretch}{1.25}" + "\n"
        r"\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}lcccc@{}}" + "\n"
        r"\toprule" + "\n"
        r"Setting & $I$ (bias$^2$) & $I$ (var) & $I_{xy}$ (var, depth) & $r^2$(bias$^2$, var) \\" + "\n"
        r"\midrule"
    )
    print(header)

    for label, suffix in _DT_SETTINGS:
        try:
            df = read_summary(f"6_class_{suffix}")
        except (FileNotFoundError, ValueError):
            continue
        row_cells = [
            label,
            mean_sd(df["bias2_moran_I"]),
            mean_sd(df["var_moran_I"]),
            mean_sd(df["var_depth_bv_moran_I"]),
            mean_sd(df["bias2_var_pearson_r2"]),
        ]
        print(" & ".join(row_cells) + r" \\")

    print(r"""\bottomrule
\end{tabular*}
\end{table}""")


def table_dt_extended():
    print(r"""\begin{table}[t]
\centering
\caption{Extended spatial diagnostics for the decision-tree generator simulation at 6
classes. $I_{xy}$ denotes bivariate Moran's $I$. IQR values are the interquartile range
of per-tree estimates across the embedding. Values are mean $\pm$ SD across 50 generators.}
\label{tab:dt-simulation-extended}
\small
\renewcommand{\arraystretch}{1.25}
\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}lcccccc@{}}
\toprule
Setting & $I_{xy}$ (var, depth) & $I_{xy}$ (var, bias$^2$) & $r^2$(bias$^2$, var) & IQR (bias$^2$) & IQR (var) & IQR (MSE) \\
\midrule""")

    for label, suffix in _DT_SETTINGS:
        try:
            df = read_summary(f"6_class_{suffix}")
        except (FileNotFoundError, ValueError):
            continue
        row_cells = [
            label,
            mean_sd(df["var_depth_bv_moran_I"]),
            mean_sd(df["var_bias2_bv_moran_I"]),
            mean_sd(df["bias2_var_pearson_r2"]),
            mean_sd(df["bias2_iqr"], digits=4),
            mean_sd(df["var_iqr"], digits=4),
            mean_sd(df["mse_iqr"], digits=4),
        ]
        print(" & ".join(row_cells) + r" \\")

    print(r"""\bottomrule
\end{tabular*}
\end{table}""")


def main():
    p = argparse.ArgumentParser(description="Print simulation tables")
    p.add_argument("--table",
                   choices=["moran-main", "enrichment", "appendix-morans", "dt", "dt-extended"],
                   default="moran-main")
    p.add_argument("--summary-dir", default=".")
    args = p.parse_args()
    global SUMMARY_DIR
    SUMMARY_DIR = Path(args.summary_dir)
    if args.table == "moran-main":
        table_moran_main()
    elif args.table == "enrichment":
        table_enrichment()
    elif args.table == "dt":
        table_dt()
    elif args.table == "dt-extended":
        table_dt_extended()
    else:
        table_appendix_morans()

if __name__ == "__main__":
    main()
